"""The formula-id -> domain-package assignment for the Formularium migration.

Hand-partitioned by physics content. The migration generator asserts exact set
equality between these keys and the catalog's formula ids, so a drifted table
fails loudly instead of silently dropping a formula.
"""

DOMAINS = (
    "electroweak",
    "flavor",
    "bz-cascade",
    "atomic",
    "em-si",
    "gravity-thermo",
    "cosmology",
    "quantum-info",
)

_PARTITION: dict[str, tuple[str, ...]] = {
    "electroweak": (
        "W_mass",
        "Z_W_ratio",
        "echarge_g",
        "echarge_gprime",
        "gf_alpha_mw",
        "higgs_mass_quartic",
        "higgs_vev_from_GF",
        "weak_mixing",
        "mass_from_yukawa",
        "yukawa_from_GF",
        "top_yukawa",
    ),
    "flavor": (
        "koide",
        "muon_electron_ratio",
        "proton_electron_ratio",
        "gatto",
        "wolfenstein_A",
        "ckm_bz",
        "nu_splitting_identity",
        "nucleon_qcd_scale",
        "qcd_transmutation",
        "yukawa_b",
        "yukawa_c",
        "yukawa_d",
        "yukawa_e",
        "yukawa_mu",
        "yukawa_s",
        "yukawa_tau",
        "yukawa_u",
    ),
    "bz-cascade": (
        "bz_scale",
        "bz_proton_seesaw",
        "higgs_seesaw_modular",
        "cascade_charm",
        "cascade_down",
        "cascade_electron",
        "cascade_muon",
        "cascade_strange",
        "cascade_up",
        "sm_decoupling_scale",
        "cc_seesaw_uvir",
    ),
    "atomic": (
        "a0_from_compton",
        "bohr_magneton",
        "bohr_radius",
        "classical_e_radius",
        "compton",
        "r_e_from_a0",
        "re_from_anomaly",
        "re_from_compton",
        "rydberg_constant",
        "rydberg_energy",
        "rydberg_from_bohr",
        "rydberg_from_compton",
        "thomson",
        "thomson_from_bohr",
        "schwinger",
    ),
    "em-si": (
        "alpha_SI",
        "alpha_from_e",
        "c_from_eps_mu",
        "faraday",
        "gas_constant",
        "impedance_from_eps",
        "vacuum_impedance",
        "schwinger_field",
        "wien",
        "stefan_boltzmann",
    ),
    "gravity-thermo": (
        "N_desitter",
        "area_quantum",
        "bekenstein_hawking",
        "clausius_horizon",
        "hawking_temperature",
        "kappa_capacity",
        "kappa_from_planck_length",
        "kappa_induced",
        "planck_from_G",
        "planck_length",
        "planck_time",
        "planck_time_from_length",
        "sbh_bits",
        "schwarzschild_area",
        "surface_gravity",
        "unruh_temperature",
    ),
    "cosmology": (
        "add_planck_dilution",
        "casimir_density",
        "casimir_throat_seesaw",
        "continuity_frw",
        "eos_dark_energy",
        "first_law_comoving",
        "friedmann_critical",
        "grav_impulse",
        "holographic_de_ansatz",
        "kk_casimir_massless",
        "lambda_from_omega",
        "rho_de_today",
        "w_capacity",
        "warp_energy_lobo_visser",
        "wormhole_mass_linear",
        "xdim_darkenergy",
    ),
    "quantum-info": (
        "brassard_threshold",
        "gie_feasibility_ratio",
        "postselected_kick",
        "tsirelson_bound",
        "tsirelson_from_chsh",
        "weak_value_projector",
    ),
}

DOMAIN_OF: dict[str, str] = {fid: domain for domain, fids in _PARTITION.items() for fid in fids}


def package_name(domain: str) -> str:
    return f"formularium-{domain}"
