"""Source emitters: specs.py, node bodies, tests, messages.proto, axiom.yaml, READMEs.

All emitters are pure string builders; migrate.py does the file IO. The emitted
packages are self-contained: no runtime dependency on sympy or on this tool —
node bodies are plain-Python arithmetic over `math`, and each package's
nodes/specs.py is the ongoing (human-editable) source of truth.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from .analysis import FormulaAnalysis
from .catalog import Constant, Quantity

SCOPE = "hamiltonjlucas"
# The shared type vocabulary (ConstantSpec, FormulaSpec, Catalog, FormulaResult,
# Empty, engine reports) lives in the proto-only formularium-types package — the
# natural boundary, restored after the platform's 10-package beta cap was lifted
# (2026-08-03). Its hand-maintained messages.proto is the vocabulary's source of
# truth; every other package (constants included) imports it from there.
TYPES_PKG = f"{SCOPE}/formularium-types"
TYPES_BINDINGS = "gen.hamiltonjlucas_formularium_types_messages_pb2"
GENERATED_BEGIN = (
    "# BEGIN GENERATED — do not hand-edit; run `formularium regen-node` after changing specs.py"
)
GENERATED_END = "# END GENERATED"


def mangle(name: str) -> str:
    """Catalog identifier -> PascalCase node/message name (letters+digits only)."""
    return "".join(part.capitalize() for part in name.split("_") if part)


def snake(pascal: str) -> str:
    """PascalCase -> snake_case, matching the axiom CLI's filename convention."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", pascal)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def constant_node_name(symbol: str) -> str:
    return "Get" + mangle(symbol)


def formula_node_name(fid: str) -> str:
    return mangle(fid)


def input_message_name(fid: str) -> str:
    return mangle(fid) + "Input"


def proto_package(pkg_name: str) -> str:
    return f"{SCOPE}.{pkg_name.replace('-', '_')}"


def _pystr(s: str | None) -> str:
    return repr(s if s is not None else "")


def _pylist(xs: list[str]) -> str:
    return "[" + ", ".join(repr(x) for x in xs) + "]"


# ---------------------------------------------------------------- messages.proto


# No package declares a local Empty: zero-argument nodes across the whole fleet share
# the one Empty type imported from formularium-types (multi-line form there — the CLI's
# proto parser does not recognize a single-line `message Empty {}`).
PROTO_HEADER = """\
// Formularium — generated by `formularium migrate`, maintained by hand alongside
// nodes/specs.py (the package's source of truth). Leading comments become registry docs.
// Shared vocabulary (Empty, ConstantSpec, FormulaResult, ...) is imported from
// formularium-types.

syntax = "proto3";

package {proto_pkg};
"""


def emit_domain_proto(pkg_name: str, analyses: list[FormulaAnalysis]) -> str:
    out = [PROTO_HEADER.format(proto_pkg=proto_package(pkg_name))]
    for a in sorted(analyses, key=lambda x: x.formula.id):
        if not a.inputs:
            continue  # zero-arity formulas take Empty
        f = a.formula
        out.append(
            f"// Inputs for {formula_node_name(f.id)} ({f.name}): computes "
            f"{a.computes} via {f.expression}. Natural units (GeV powers)."
        )
        out.append(f"message {input_message_name(f.id)} {{")
        for i, sym in enumerate(a.inputs, start=1):
            out.append(f"  double {sym} = {i};")
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit_constants_proto(pkg_name: str) -> str:
    """Constants declares no local messages: ConstantSpec, Catalog, and Empty all come
    from formularium-types, like every other package's shared types."""
    return PROTO_HEADER.format(proto_pkg=proto_package(pkg_name))


# ---------------------------------------------------------------- specs.py


_FORMULA_SPEC_CLASS = """\
@dataclass(frozen=True)
class FormulaSpec:
    id: str
    name: str
    expression: str          # sympy-parseable "Eq(lhs, rhs)" — THE formula
    symbols: list[str]       # every catalog symbol the expression touches
    input_symbols: list[str] # RHS free symbols, sorted — the node's input fields
    computes: str            # str(lhs): what the node's FormulaResult.value is
    tier: str                # established | derived | conjecture
    provenance: str
    refs: list[str]
    notes: str
    dimensional_check: str
    domain: str = DOMAIN


@dataclass(frozen=True)
class QuantitySpec:
    symbol: str
    name: str
    mass_dim: float
    kind: str                # parameter | coupling | observable | derived
    notes: str
"""


def emit_domain_specs(
    domain: str, analyses: list[FormulaAnalysis], quantities: list[Quantity]
) -> str:
    lines = [
        f'"""Formularium {domain} — the source of truth for this package\'s formulas.',
        "",
        "Edit entries here directly (tier, provenance, notes, or the expression itself).",
        "After changing an `expression`, run `formularium regen-node <pkg-dir> <formula-id>`",
        "to re-derive the node's arithmetic; `formularium check-specs` (pre-commit) verifies",
        "node bodies stay consistent with these specs.",
        '"""',
        "",
        "from dataclasses import dataclass",
        "",
        f"DOMAIN = {_pystr(domain)}",
        "",
        "",
        _FORMULA_SPEC_CLASS,
        "",
        "FORMULAS: dict[str, FormulaSpec] = {",
    ]
    for a in sorted(analyses, key=lambda x: x.formula.id):
        f = a.formula
        all_syms = sorted({str(s) for s in a.eq.lhs.free_symbols} | set(a.inputs))
        lines += [
            f"    {_pystr(f.id)}: FormulaSpec(",
            f"        id={_pystr(f.id)},",
            f"        name={_pystr(f.name)},",
            f"        expression={_pystr(f.expression)},",
            f"        symbols={_pylist(all_syms)},",
            f"        input_symbols={_pylist(a.inputs)},",
            f"        computes={_pystr(a.computes)},",
            f"        tier={_pystr(f.tier)},",
            f"        provenance={_pystr(f.provenance)},",
            f"        refs={_pylist(f.refs)},",
            f"        notes={_pystr(f.notes)},",
            f"        dimensional_check={_pystr(f.dimensional_check)},",
            "    ),",
        ]
    lines.append("}")
    lines += ["", "", "QUANTITIES: dict[str, QuantitySpec] = {"]
    for q in sorted(quantities, key=lambda q: q.symbol):
        lines += [
            f"    {_pystr(q.symbol)}: QuantitySpec(",
            f"        symbol={_pystr(q.symbol)},",
            f"        name={_pystr(q.name)},",
            f"        mass_dim={q.mass_dim!r},",
            f"        kind={_pystr(q.kind)},",
            f"        notes={_pystr(q.notes)},",
            "    ),",
        ]
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit_constants_specs(constants: list[Constant]) -> str:
    lines = [
        '"""Formularium constants — the source of truth for every catalog constant.',
        "",
        "Edit entries here directly (values, uncertainties, tiers, notes). The Get* nodes",
        "and GetCatalog marshal these specs verbatim; `formularium regen-node` regenerates",
        "the node files wholesale if entries are added or removed.",
        '"""',
        "",
        "from dataclasses import dataclass, field",
        "",
        "",
        "@dataclass(frozen=True)",
        "class ConstantSpec:",
        "    symbol: str",
        "    name: str",
        "    value: float             # in `unit`",
        "    unit: str",
        "    mass_dim: float          # natural units (hbar = c = 1); dimensionless iff 0",
        "    tier: str                # established | derived | conjecture",
        "    source: str              # CODATA | PDG | NuFIT | Planck | derived | definition | convention",
        "    uncertainty: float | None = None",
        "    aliases: list[str] = field(default_factory=list)",
        "    notes: str = ''",
        "    related_formulas: list[str] = field(default_factory=list)",
        "",
        "",
        "CONSTANTS: dict[str, ConstantSpec] = {",
    ]
    for c in sorted(constants, key=lambda c: c.symbol):
        lines += [
            f"    {_pystr(c.symbol)}: ConstantSpec(",
            f"        symbol={_pystr(c.symbol)},",
            f"        name={_pystr(c.name)},",
            f"        value={float(c.value)!r},",
            f"        unit={_pystr(c.unit)},",
            f"        mass_dim={c.mass_dim!r},",
            f"        tier={_pystr(c.tier)},",
            f"        source={_pystr(c.source)},",
        ]
        if c.uncertainty is not None:
            lines.append(f"        uncertainty={float(c.uncertainty)!r},")
        if c.aliases:
            lines.append(f"        aliases={_pylist(c.aliases)},")
        if c.notes:
            lines.append(f"        notes={_pystr(c.notes)},")
        if c.related_formulas:
            lines.append(f"        related_formulas={_pylist(c.related_formulas)},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- node files


def emit_formula_node(a: FormulaAnalysis) -> str:
    f = a.formula
    node = formula_node_name(f.id)
    fn = snake(node)
    input_msg = input_message_name(f.id) if a.inputs else "Empty"
    doc = (
        f"{f.name} — {f.tier}. Computes {a.computes} = {a.eq.rhs!s} in natural units (GeV powers)."
    )
    body = a.rendered
    uses_math = "math." in body
    lines = []
    if uses_math:
        lines += ["import math", ""]
    input_import = (
        f"from gen.messages_pb2 import {input_msg}"
        if a.inputs
        else f"from {TYPES_BINDINGS} import Empty"
    )
    lines += [
        "from gen.axiom_context import AxiomContext",
        f"from {TYPES_BINDINGS} import FormulaResult",
        input_import,
        "from nodes.specs import FORMULAS",
        "",
        f"SPEC = FORMULAS[{_pystr(f.id)}]",
        "",
        "",
        f"def {fn}(ax: AxiomContext, input: {input_msg}) -> FormulaResult:",
        f'    """{doc}"""',
        f"    {GENERATED_BEGIN}",
        f"    value = {body}",
        f"    {GENERATED_END}",
        "    return FormulaResult(value=value, formula_id=SPEC.id,",
        "                         computes=SPEC.computes, tier=SPEC.tier)",
        "",
    ]
    return "\n".join(lines)


def emit_constant_node(c: Constant) -> str:
    node = constant_node_name(c.symbol)
    fn = snake(node)
    unc = f" ± {c.uncertainty:g}" if c.uncertainty is not None else ""
    doc = f"{c.name}: {c.value:g}{unc} {c.unit} ({c.source}, {c.tier}). Returns the full spec."
    return "\n".join(
        [
            "from gen.axiom_context import AxiomContext",
            f"from {TYPES_BINDINGS} import ConstantSpec, Empty",
            "from nodes.specs import CONSTANTS",
            "",
            f"SPEC = CONSTANTS[{_pystr(c.symbol)}]",
            "",
            "",
            f"def {fn}(ax: AxiomContext, input: Empty) -> ConstantSpec:",
            f'    """{doc}"""',
            "    m = ConstantSpec(",
            "        symbol=SPEC.symbol, name=SPEC.name, value=SPEC.value, unit=SPEC.unit,",
            "        mass_dim=SPEC.mass_dim, tier=SPEC.tier, source=SPEC.source,",
            "        aliases=SPEC.aliases, notes=SPEC.notes,",
            "        related_formulas=SPEC.related_formulas,",
            "    )",
            "    if SPEC.uncertainty is not None:",
            "        m.uncertainty = SPEC.uncertainty",
            "    return m",
            "",
        ]
    )


def emit_domain_get_catalog(domain: str) -> str:
    return "\n".join(
        [
            "from gen.axiom_context import AxiomContext",
            f"from {TYPES_BINDINGS} import DomainCatalog, Empty",
            "from nodes.specs import DOMAIN, FORMULAS, QUANTITIES",
            "",
            "",
            "def get_catalog(ax: AxiomContext, input: Empty) -> DomainCatalog:",
            (
                f'    """The Formularium {domain} domain catalog: every formula spec '
                'and the quantities they reference."""'
            ),
            "    m = DomainCatalog(domain=DOMAIN)",
            "    for f in FORMULAS.values():",
            "        m.formulas.add(",
            "            id=f.id, name=f.name, expression=f.expression, symbols=f.symbols,",
            "            input_symbols=f.input_symbols, computes=f.computes, tier=f.tier,",
            "            provenance=f.provenance, refs=f.refs, notes=f.notes,",
            "            dimensional_check=f.dimensional_check, domain=f.domain,",
            "        )",
            "    for q in QUANTITIES.values():",
            "        m.quantities.add(symbol=q.symbol, name=q.name, mass_dim=q.mass_dim,",
            "                         kind=q.kind, notes=q.notes)",
            "    return m",
            "",
        ]
    )


def emit_constants_get_catalog() -> str:
    return "\n".join(
        [
            "from gen.axiom_context import AxiomContext",
            f"from {TYPES_BINDINGS} import Catalog, Empty",
            "from nodes.specs import CONSTANTS",
            "",
            "",
            "def get_catalog(ax: AxiomContext, input: Empty) -> Catalog:",
            (
                '    """Every Formularium constant spec, as a Catalog (domain slices '
                'left to the domain packages)."""'
            ),
            "    m = Catalog()",
            "    for c in CONSTANTS.values():",
            "        entry = m.constants.add(",
            "            symbol=c.symbol, name=c.name, value=c.value, unit=c.unit,",
            "            mass_dim=c.mass_dim, tier=c.tier, source=c.source,",
            "            aliases=c.aliases, notes=c.notes,",
            "            related_formulas=c.related_formulas,",
            "        )",
            "        if c.uncertainty is not None:",
            "            entry.uncertainty = c.uncertainty",
            "    return m",
            "",
        ]
    )


# ---------------------------------------------------------------- tests


def emit_formula_test(
    a: FormulaAnalysis,
    input_values: dict[str, float],
    expected: float,
    sanity_target: float | None,
) -> str:
    f = a.formula
    node = formula_node_name(f.id)
    fn = snake(node)
    input_msg = input_message_name(f.id) if a.inputs else "Empty"
    kwargs = ", ".join(f"{s}={input_values[s]!r}" for s in a.inputs)
    lines = [
        "# Generated numeric regression tests — the migration-fidelity gate.",
        "# `transcription` pins the node body to the spec expression at generation-time",
        "# reference values; `physics_sanity` (where present) checks the computed value",
        "# against the measured catalog constant (loose: loop corrections are real).",
        (
            f"from gen.messages_pb2 import {input_msg}"
            if a.inputs
            else f"from {TYPES_BINDINGS} import Empty"
        ),
        f"from nodes.{fn} import {fn}",
        "",
        "",
        f"def test_{fn}_transcription():",
        f"    result = {fn}(None, {input_msg}({kwargs}))",
        f"    assert result.formula_id == {_pystr(f.id)}",
        f"    assert result.computes == {_pystr(a.computes)}",
        f"    assert result.tier == {_pystr(f.tier)}",
    ]
    if expected == 0:
        lines.append("    assert abs(result.value) < 1e-12")
    else:
        lines += [
            f"    expected = {expected!r}",
            "    assert abs(result.value / expected - 1.0) < 1e-9",
        ]
    if sanity_target is not None and sanity_target != 0:
        lines += [
            "",
            "",
            f"def test_{fn}_physics_sanity():",
            f"    result = {fn}(None, {input_msg}({kwargs}))",
            f"    catalog_value = {sanity_target!r}  # measured, natural units",
            "    assert abs(result.value / catalog_value - 1.0) < 0.25",
        ]
    lines.append("")
    return "\n".join(lines)


def emit_constant_test(c: Constant) -> str:
    node = constant_node_name(c.symbol)
    fn = snake(node)
    lines = [
        f"from {TYPES_BINDINGS} import Empty",
        f"from nodes.{fn} import {fn}",
        "",
        "",
        f"def test_{fn}():",
        f"    spec = {fn}(None, Empty())",
        f"    assert spec.symbol == {_pystr(c.symbol)}",
        f"    assert spec.value == {float(c.value)!r}",
        f"    assert spec.unit == {_pystr(c.unit)}",
        f"    assert spec.tier == {_pystr(c.tier)}",
        f"    assert spec.source == {_pystr(c.source)}",
        f"    assert spec.mass_dim == {c.mass_dim!r}",
    ]
    if c.uncertainty is not None:
        lines.append(f"    assert spec.uncertainty == {float(c.uncertainty)!r}")
    lines.append("")
    return "\n".join(lines)


def emit_domain_get_catalog_test(domain: str, n_formulas: int, n_quantities: int) -> str:
    return "\n".join(
        [
            f"from {TYPES_BINDINGS} import Empty",
            "from nodes.get_catalog import get_catalog",
            "",
            "",
            "def test_get_catalog():",
            "    m = get_catalog(None, Empty())",
            f"    assert m.domain == {_pystr(domain)}",
            f"    assert len(m.formulas) == {n_formulas}",
            f"    assert len(m.quantities) == {n_quantities}",
            "    ids = {f.id for f in m.formulas}",
            f"    assert len(ids) == {n_formulas}",
            "    assert all(f.expression.startswith('Eq(') for f in m.formulas)",
            "",
        ]
    )


def emit_constants_get_catalog_test(n_constants: int) -> str:
    return "\n".join(
        [
            f"from {TYPES_BINDINGS} import Empty",
            "from nodes.get_catalog import get_catalog",
            "",
            "",
            "def test_get_catalog():",
            "    m = get_catalog(None, Empty())",
            f"    assert len(m.constants) == {n_constants}",
            "    assert len(m.domains) == 0",
            "    symbols = {c.symbol for c in m.constants}",
            f"    assert len(symbols) == {n_constants}",
            "",
        ]
    )


# ---------------------------------------------------------------- README


@dataclass
class ReadmeRow:
    left: str
    name: str
    tier: str
    extra: str


def emit_domain_readme(pkg_name: str, domain: str, analyses: list[FormulaAnalysis]) -> str:
    rows = "\n".join(
        f"| `{formula_node_name(a.formula.id)}` | {a.formula.name} | {a.formula.tier} "
        f"| `{a.computes} = {a.eq.rhs}` |"
        for a in sorted(analyses, key=lambda x: x.formula.id)
    )
    return f"""# {pkg_name}

**Formularium** {domain} formulas as [Axiom](https://dev.axiomide.com) compute nodes —
part of an axiom-native physics catalog where the packages themselves are the source
of truth ({len(analyses)} formulas in this domain).

Each node takes the formula's right-hand-side symbols as `double` inputs in **natural
units** (ħ = c = 1, GeV powers) and returns the shared
`formularium-types.FormulaResult {{value, formula_id, computes, tier}}`. The `GetCatalog`
node returns this package's full `DomainCatalog` (formula specs + referenced quantities)
for catalog assembly.

| Node | Formula | Tier | Computes |
|---|---|---|---|
{rows}

Input field names preserve catalog symbol spelling (`M_W`, not `m_w`) — fidelity over
proto naming convention, by design.

The machine-readable source of truth is [`nodes/specs.py`](nodes/specs.py); node
arithmetic is generated from it and kept consistent by `formularium check-specs`.
Part of the [Formularium](https://github.com/hamiltonjlucas/formularium) project,
migrated from the file-based *unified-theory* catalog.

License: Apache-2.0.
"""


def emit_constants_readme(pkg_name: str, constants: list[Constant]) -> str:
    rows = "\n".join(
        f"| `{constant_node_name(c.symbol)}` | {c.symbol} | {c.name} | {c.value:g} {c.unit} "
        f"| {c.source} |"
        for c in sorted(constants, key=lambda c: c.symbol)
    )
    return f"""# {pkg_name}

**Formularium** physical constants as [Axiom](https://dev.axiomide.com) nodes — one
`Get*` node per constant ({len(constants)} total) returning the full
`formularium-types.ConstantSpec` (value, uncertainty, unit, natural-units mass
dimension, tier, source), plus `GetCatalog` returning every constant at once.

The shared protobuf contracts (`ConstantSpec`, `FormulaSpec`, `Catalog`,
`FormulaResult`, the engine report messages) live in the proto-only
[`formularium-types`](https://github.com/hamiltonjlucas/formularium-types) package,
which this package — like every other in the fleet — `axiom import`s.

| Node | Symbol | Name | Value | Source |
|---|---|---|---|---|
{rows}

The machine-readable source of truth is [`nodes/specs.py`](nodes/specs.py).
Part of the [Formularium](https://github.com/hamiltonjlucas/formularium) project.

License: Apache-2.0.
"""
