"""Fleet orchestration: GitHub repos, validate/push/publish across all packages.

Push order respects dependencies: formularium-types first (every other package
imports it), then constants + the 8 domain packages, then formularium-engine.
Every push step commits and pushes git first — the platform builds from the
remote HEAD, never the working tree.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from .domains import DOMAINS
from .emit import SCOPE

TYPES = "formularium-types"
CONSTANTS = "formularium-constants"
ENGINE = "formularium-engine"
DOMAIN_PKGS = [f"formularium-{d}" for d in DOMAINS]
ALL_PACKAGES = [TYPES, CONSTANTS, *DOMAIN_PKGS, ENGINE]
PUSH_ORDER = [[TYPES], [CONSTANTS, *DOMAIN_PKGS], [ENGINE]]

TOOLING_DIR = Path(__file__).resolve().parents[2]

PRE_COMMIT_HOOK = f"""#!/bin/sh
# Formularium: verify node bodies match nodes/specs.py before committing.
exec uv run --project {TOOLING_DIR} formularium check-specs "$(git rev-parse --show-toplevel)"
"""


def _run(cmd: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=check)


def _existing(out_root: Path, names: list[str] | None = None) -> list[Path]:
    return [out_root / p for p in (names or ALL_PACKAGES) if (out_root / p / "axiom.yaml").exists()]


def repo_sync(out_root: Path, only: str | None = None) -> int:
    """Idempotent: git init, GitHub repo, https-fetch/ssh-push origin, pre-commit hook."""
    rc = 0
    for pkg_dir in _existing(out_root, [only] if only else None):
        name = pkg_dir.name
        if not (pkg_dir / ".git").exists():
            _run(["git", "init", "-b", "main"], cwd=pkg_dir)
            print(f"{name}: git init")
        remotes = _run(["git", "remote"], cwd=pkg_dir).stdout.split()
        if "origin" not in remotes:
            _run(["git", "add", "-A"], cwd=pkg_dir)
            if _run(["git", "status", "--porcelain"], cwd=pkg_dir).stdout.strip():
                _run(
                    [
                        "git",
                        "commit",
                        "-m",
                        (
                            f"{name}: initial Formularium package source\n\n"
                            "Generated by `formularium migrate` from the unified-theory "
                            "catalog.\n\n"
                            "Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>"
                        ),
                    ],
                    cwd=pkg_dir,
                )
            create = _run(
                [
                    "gh",
                    "repo",
                    "create",
                    f"{SCOPE}/{name}",
                    "--public",
                    "--description",
                    f"Formularium: {name} (axiom-native physics catalog)",
                    "--source",
                    ".",
                    "--push",
                ],
                cwd=pkg_dir,
                check=False,
            )
            if create.returncode != 0:
                print(f"{name}: gh repo create FAILED: {create.stderr.strip()}")
                rc = 1
                continue
            print(f"{name}: created github.com/{SCOPE}/{name} and pushed")
        # the platform clones the fetch URL: must be https; keep pushes on ssh
        _run(
            ["git", "remote", "set-url", "origin", f"https://github.com/{SCOPE}/{name}.git"],
            cwd=pkg_dir,
        )
        _run(
            ["git", "remote", "set-url", "--push", "origin", f"git@github.com:{SCOPE}/{name}.git"],
            cwd=pkg_dir,
        )
        if (pkg_dir / "nodes" / "specs.py").exists():
            hook = pkg_dir / ".git" / "hooks" / "pre-commit"
            hook.write_text(PRE_COMMIT_HOOK)
            hook.chmod(0o755)
        print(f"{name}: origin wired (https fetch, ssh push), hook installed")
    return rc


def validate_all(out_root: Path) -> int:
    rc = 0
    for pkg_dir in _existing(out_root):
        out = _run(["axiom", "validate", "--json"], cwd=pkg_dir, check=False)
        try:
            passed = json.loads(out.stdout).get("passed", False)
        except json.JSONDecodeError:
            passed = False
        print(f"{pkg_dir.name}: {'passed' if passed else 'FAILED'}")
        if not passed:
            rc = 1
    return rc


def _git_commit_push(pkg_dir: Path, message: str) -> bool:
    _run(["git", "add", "-A"], cwd=pkg_dir)
    if _run(["git", "status", "--porcelain"], cwd=pkg_dir).stdout.strip():
        commit = _run(
            [
                "git",
                "commit",
                "-m",
                f"{message}\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>",
            ],
            cwd=pkg_dir,
            check=False,
        )
        if commit.returncode != 0:
            print(f"{pkg_dir.name}: git commit failed: {commit.stderr.strip()}")
            return False
    push = _run(["git", "push", "-u", "origin", "main"], cwd=pkg_dir, check=False)
    if push.returncode != 0:
        print(f"{pkg_dir.name}: git push failed: {push.stderr.strip()}")
        return False
    return True


def push_all(out_root: Path, only: str | None = None) -> int:
    for stage in PUSH_ORDER:
        for pkg_dir in _existing(out_root, [p for p in stage if only in (None, p)]):
            if not _git_commit_push(pkg_dir, f"{pkg_dir.name}: update package source"):
                return 1
            out = _run(["axiom", "push", "--json"], cwd=pkg_dir, check=False)
            try:
                res = json.loads(out.stdout.strip().splitlines()[-1])
            except (json.JSONDecodeError, IndexError):
                res = {}
            if res.get("success"):
                print(f"{pkg_dir.name}: pushed {res.get('version')}")
            else:
                print(
                    f"{pkg_dir.name}: PUSH FAILED: {res.get('error') or out.stdout or out.stderr}"
                )
                return 1
    return 0


def publish_all(out_root: Path) -> int:
    for stage in PUSH_ORDER:
        for pkg_dir in _existing(out_root, stage):
            version = None
            for line in (pkg_dir / "axiom.yaml").read_text().splitlines():
                if line.startswith("version:"):
                    version = line.split(":", 1)[1].strip()
            ref = f"{SCOPE}/{pkg_dir.name}@{version}"
            out = _run(["axiom", "publish", ref, "--yes"], cwd=pkg_dir, check=False)
            if out.returncode != 0:
                already = "already" in (out.stdout + out.stderr).lower()
                print(
                    f"{pkg_dir.name}: publish {'skipped (already published)' if already else 'FAILED'}"
                    f"{'' if already else ': ' + (out.stdout + out.stderr).strip()[:300]}"
                )
                if not already:
                    return 1
            else:
                print(f"{pkg_dir.name}: published {ref}")
    return 0
